### ISSUE TITLE
Failed to load the linter-stylelint package

### ISSUE THREAD

**Issue by ismay** [1000ch/linter-stylelint#1]
I was trying out your plugin, but it threw an error after I installed it: `cannot find module `atom-linter`. Here's my atom error report:

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [linter-stylelint](git+https://github.com/1000ch/linter-stylelint) package, v0.2.3

### Stack Trace

Failed to load the linter-stylelint package

```
At Cannot find module 'atom-linter'

Error: Cannot find module 'atom-linter'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/ismay/.atom/packages/linter-stylelint/index.js:17:19)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/babel.js:166:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:188:28
  at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.load (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:179:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:372:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:451:30)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:368:29
  at exit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:59:16)
  at triggerExitCallback (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -0:30.8.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:17.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
editorconfig, v1.0.1
highlight-selected, v0.10.1
linter, v1.2.4
linter-eslint, v3.0.1
linter-stylelint, v0.2.3
minimap, v4.12.0

# Dev
No dev packages
```

**Comment by 1000ch** [comment]
@ismay Sorry, I fixed this problem and published as `0.2.4`. Please try this?

**Comment by ismay** [comment]
This solved it, thanks!

**Comment by 1000ch** [comment]
:+1:

**Comment by tsbarnes** [comment]
I'm currently having this issue, on Ubuntu 15.04 using Atom 1.0.11.  I've got linter-stylelint 1.0.0 and linter 1.5.1.

**Comment by petervansark** [comment]
I'm having the same issue on Ubuntu 14.04 with Atom 1.0.11. Using linter-stylelint 1.0.0 and linter 1.5.1.

**Comment by 1000ch** [comment]
@tsbarnes @petervansark please reinstall `v1.0.2`?

**Comment by tsbarnes** [comment]
The error is gone and the package is working after installing 1.0.2.

**Comment by 1000ch** [comment]
:+1:

**Comment by petervansark** [comment]
Works again! :+1:
Thanks!

**Comment by mech** [comment]
Somehow the linter refuse to load due to one-color's One-com/one-color#22, anyone encounter it also?

```
At Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".


EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at Function (native)
    at installColorSpace (/Users/mech/.atom/packages/linter-stylelint/node_modules/stylelint/node_modules/colorguard/node_modules/pipetteur/node_modules/onecolor/one-color-all-debug.js:97:32)
    at Object.<anonymous> (/Users/mech/.atom/packages/linter-stylelint/node_modules/stylelint/node_modules/colorguard/node_modules/pipetteur/node_modules/onecolor/one-color-all-debug.js:218:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
...
```

**Comment by ilikescience** [comment]
@mech I also encountered this issue. Unsure of how to fix. Any help?

**Comment by Arcanemagus** [comment]
@mech see https://github.com/stylelint/stylelint/issues/891 for more details, I think I'm going to release a version that pins stylelint...

**Comment by mech** [comment]
@Arcanemagus Tks much for the heads-up!

**Comment by Arcanemagus** [comment]
v1.14.0 published pinning the `stylelint` version, sorry it took so long!

**Comment by mech** [comment]
Strange somehow I have this `Undefined rule "declaration-block-no-shorthand-property-overrides"`. I am using just this on my `.stylelintrc`:

```
{
  "extends": "stylelint-config-standard"
}
```

**Comment by ntwb** [comment]
@mech `declaration-block-no-shorthand-property-overrides` was added in stylelint 4.5.0

It replaced the deprecated `rule-no-shorthand-property-overrides` rule.

I'd say that `stylelint-config-standard` v4.0.0 is in `.atom/packages/linter-stylelint/node_modules`

**Comment by Arcanemagus** [comment]
Yea, definitely looks like you manually installed that at some point and `apm` for some reason didn't install a compatible version when updating (not surprising with the other bugs it has with that...).

If you have Node.js installed simply run `npm install` in the package directory, or just uninstall and re-install  the package.

**Comment by mech** [comment]
I have install a new Node using nvm, then delete my local project's `node_modules` and `npm install` again. I make sure my global do not have anything unusual installed. Then I uninstall and install the Atom linter-styelint again. I have the same result. I am using:

```
// In my package.json
"stylelint": "^4.5.1",
"stylelint-config-standard": "^4.0.0"
```

And linter-stylelint is at version 1.14.0.

@ntwb I look at the `.atom/packages/linter-stylelint/node_modules` and it says it was on version 3.0.0.

I also have my `.stylelintrc` on my project folder. I think the linter will respect that usually right?

**Comment by ntwb** [comment]
I'm pretty sure Atom will be picking up `"stylelint-config-standard": "^4.0.0"` from your project, you should change your project back to `"stylelint-config-standard": "^3.0.0"` until all of this is sorted out.
